name: Run Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NPM_TOKEN: ""

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: 18
          cache: yarn
      - uses: borales/actions-yarn@v3.0.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        name: Run TypeScript check
        with:
          cmd: test:tsc
